### ISSUE TITLE
Bruh , 

### ISSUE THREAD

**Issue by YogPanjarale** [Shobhit-Nagpal/calculator#1]
https://github.com/Shobhit-Nagpal/calculator/blob/9b750f5861b81e010e7f4051c3aa582786e9df21/script.js#L60

This is not how you are supposed to do it 
Either 
```js
displayValue.innerHTML += button.id
// if button.id is a operator run it through a another logic

**Comment by Shobhit-Nagpal** [comment]
Yes, fixed it. Thank you, sir :)
